apiVersion: v1
kind: Service
metadata:
  name: mcp-server-sse
  labels:
    app: mcp-server-sse
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: mcp-server-sse
